### ISSUE TITLE
error while creating the environment in the Anaconda

### ISSUE THREAD

**Issue by mashrur93** [sebhoerl/boptx#1]
Hi, I was trying to explore the py codes for the MATSIM calibration purpose. However, while importing the environment.yml file, the following error pops up.

ResolvePackageNotFound: 
- deepmerge=0.3.0
- python=3.9.9

I am using Anaconda with python 3.9.12 version. Any help in this regard would be highly appreciated. Thanks

**Comment by sebhoerl** [comment]
Hi, I'm still in the process of cleaning up the repository. Thanks for already testing it out.
The environment.yml is based on a recent version of Mamba from mamba-forge, maybe this makes the difference. If Python is the problem, you can just try to remove it from the environment file. The Python version should not make too much of a difference. For deepmerge, maybe just remove it from the dependencies and then install it manually with whatever version is proposed by Anaconda.

**Comment by mashrur93** [comment]
Thanks a lot for the quick response. I updated the environment's Python version with Anaconda's Python version and removed the deepmerge. Finally, Anaconda imported the environment without the error.
